### ISSUE TITLE
[hal] Rename Targets, Processors, Clusters and Cores

### ISSUE THREAD

**Issue by ppenna** [nanvix/hal#112]
Description
---------------

We should embrace the following standard naming scheme for targets, processors, clusters and cores.

**Targets**

- OpTimSoC (optimsoc)
- MPPA-256 (mppa256)
- QEMU OpenRISC (qemu-openrisc)
- QEMU x86 (qemu-x86)

**Processors**

- OpTiMSoC 4 Cores (optimsoc4)
- Bostan (bostan)
- OpenRISC (openrisc)
- x86 (x86)

**Clusters**

- Bostan Cluster (k1b-cluster)
- Bostan I/O Cluster (k1bio)
- Bostan Compute Cluster (k1bdp)
- OpenRISC Cluster (or1k-smp)
- x86 Cluster (x86-smp)

**Cores**

- Bostan Core (k1b)
- OpenRISC Core (or1k)
- OpenRISC OR1200 Core (or1200)
- OpenRISC MOR1KX Core (mor1kx)
- Intel 80486 Core (i486)

**Comment by ppenna** [comment]
@joaovicentesouto and @Theldus I would love inputs on this =)

**Comment by Theldus** [comment]
Well, I agree with this standard naming and having documented like this, will help a lot.
