### ISSUE TITLE
[or1k-core] Locking Same Entry of Cores Table Twice

### ISSUE THREAD

**Issue by ppenna** [nanvix/hal#124]
Description
----------------

In the current implementation of the Core Interface for or1k cores,  we are locking twice the same entry of the cores table, when calling `or1k_core_idle()` from `or1k_core_reset()`. Since spinlocks are not re-entrant, we end up freezing the core.

```
PUBLIC void or1k_core_idle(void)
{
	int coreid = or1k_core_get_id();

	or1k_spinlock_lock(&cores[coreid].lock);
	
	...
}

PUBLIC void or1k_core_reset(void)
{
	int coreid = or1k_core_get_id();

	or1k_spinlock_lock(&cores[coreid].lock);
	
	...
}
```

**Comment by Theldus** [comment]
Maybe the k1b also have this issue, since the or1k implementation was based from there.
