### ISSUE TITLE
[or1k-core] Missing Spinlock Memory Barrier

### ISSUE THREAD

**Issue by ppenna** [nanvix/hal#175]
Description
------------------

In the current implementation of the Spinlock Interface for OpenRISC cores, we are missing a memory barrier when locking and unlocking a Spinlock. That is, registers are no flushed into memory before lock/unlock.

**Comment by ppenna** [comment]
@Theldus does the OpenRISC toolchain supports builtin atomics? If so, it would be nice to switch to them....

**Comment by Theldus** [comment]
I do not know, I have to check, if so, it's better to rely on it instead of using ours.

**Comment by ppenna** [comment]
@Theldus I am pretty much sure, because atomic instructions are supported.... Could you just try to use the builtin functions and see how it goes? Deep research will take longe r=p
