### ISSUE TITLE
[hal] Mailbox Interface

### ISSUE THREAD

**Issue by joaovicentesouto** [nanvix/hal#182]
## Description
The Mailbox Interface exposes the mailbox abstraction and routines to operate on it. Overall the following interface is exposed.

**Constants**

- `MAILBOX_CREATE_MAX`: maximum number of mailbox to create
- `MAILBOX_OPEN_MAX`: maximum number of mailbox to open
- `MAILBOX_MSG_SIZE`: size (in bytes) of a mailbox message.

**Functions**

- `mailbox_create()`: creates an input mailbox
- `mailbox_open()`: opens an output mailbox
- `mailbox_unlink()`: destroys an input mailbox
- `mailbox_close()`: closes an input mailbox
- `mailbox_write()`: writes a message to an output mailbox
- `mailbox_read()`: reads a message from an input mailbox

History of Changes
---------------------------

1. Initial Mailbox Interface Specification

**Comment by ppenna** [comment]
@joaovicentesouto, in order to follow a new standard, could you please path the interface and the current Inplementation for bostan so as to remove the "hal_" prefix?

**Comment by joaovicentesouto** [comment]
Of course!
