### ISSUE TITLE
[hal] Huge Page Support

### ISSUE THREAD

**Issue by ppenna** [nanvix/hal#269]
Description
-------------------

Currently, the MMU Interface exposes a two-level paging scheme with a standard page size.

Nevertheless, some supported atchitecures enable a hybrid scheme with huge pages, which we lack on support.

Road Map
--------------

- [x] OpenRISC Cluster (b83de03730a9589637b5215b2c3f5e5505fc7353)
- [x] OpTiMSoC Cluster (b83de03730a9589637b5215b2c3f5e5505fc7353)
- [x] RISC-V 32-Bit Cluster (d2726d17c0a0b931b4c15a26bbb21466d5f20208)

**Comment by Theldus** [comment]
OpenRISC also has huge pages, though its huge pages are really huge (16MB). It might be a good idea to consider using them in or1k (or not) when MMU supports huge pages.

**Comment by ppenna** [comment]
@Theldus I tagged OpenRISC base plataforms so =)
