### ISSUE TITLE
[or1k] Clock Interface Ignores Supplied Frequency

### ISSUE THREAD

**Issue by ppenna** [nanvix/hal#345]
Description
---------------

Currently, the `or1k_clock_init()` ignores the supplied frequency (https://github.com/nanvix/hal/blob/unstable/src/hal/arch/core/or1k/clock.c#L92).

**Comment by Theldus** [comment]
This was intended ... because some time ago we were experiencing problems in the '/' operator (until we discovered the lack of extbs instruction in OpTiMSoC), so at that time we could not adjust the frequency using the parameter provided.

As the division operation works now, I'll fix that later.
