### ISSUE TITLE
[linux64-core] Wrong Core Type for word_t

### ISSUE THREAD

**Issue by joaovicentesouto** [nanvix/hal#608]
## Description

The Bit-Lenght of `word_t` in `linux64` is:
```c
#define LINUX64_WORD_BIT   32 /**< Word        */
```
But, we are using `uint64_t` instead of `uint32_t` to define the core type:
```c
typedef uint64_t linux64_word_t;  /**< Word        */
```

## Observation

We must verify that is the correct core type or this is a bug and we need change to 32 bits.

**Comment by ppenna** [comment]
@joaovicentesouto I'm gonna take a look on this =)
